# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pictrait' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftHTTP', '~> 2.0.0'
pod ‘SwiftSpinner’
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~> 4.0'

  # Pods for Pictrait

  target 'PictraitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PictraitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
